services:
  - type: web
    name: simupay-backend
    runtime: node
    plan: free
    root: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        scope: run
      - key: ACCESS_TOKEN_SECRET
        scope: run
      - key: REFRESH_TOKEN_SECRET
        scope: run
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
