CREATE TYPE "TransactionType" AS ENUM ('TRANSFER', 'DEPOSIT', 'WITHDRAWAL');

ALTER TABLE "Transaction"
  ADD COLUMN "type" "TransactionType" NOT NULL DEFAULT 'TRANSFER',
  ALTER COLUMN "amount" TYPE DOUBLE PRECISION USING "amount"::DOUBLE PRECISION,
  ALTER COLUMN "fee" TYPE DOUBLE PRECISION USING "fee"::DOUBLE PRECISION,
  ALTER COLUMN "senderId" DROP NOT NULL,
  ALTER COLUMN "receiverId" DROP NOT NULL;
